spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # default
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.8
          responseFormat:
            type: JSON_OBJECT
      image:
        options:
          model: dall-e-3
          size: 1024x1024
          response-format: b64_json
    retry:
      max-attempts: 5

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    org.springframework.ai.openai: DEBUG
    org.springframework.ai.chat: DEBUG
    org.springframework.ai.image: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app}

cloud:
  aws:
    s3:
      bucket: moavoca-dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://moavoca-rds.c9ac4wwc0hi3.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: app
    password: ${DB_PASSWORD}

cloud:
  aws:
    s3:
      bucket: moavoca-prod
